name: ECS CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ecs-deploy
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  ECR_REPO: ecs-fargate
  ECS_CLUSTER: fargate-example
  ECS_SERVICE: fargate-ecs-service

#################################################
# JOB 1 — Checkout
#################################################
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#################################################
# JOB 2 — Configure AWS
#################################################
  configure-aws:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::227224898353:role/dev-ecs_fargate
          aws-region: ${{ env.AWS_REGION }}

#################################################
# JOB 3 — Login to ECR
#################################################
  ecr-login:
    needs: configure-aws
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login.outputs.registry }}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::227224898353:role/dev-ecs_fargate
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

#################################################
# JOB 4 — Build & Push Image
#################################################
  build-push:
    needs: ecr-login
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build.outputs.image_uri }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::227224898353:role/dev-ecs_fargate
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        id: build
        run: |
          IMAGE_URI=${{ needs.ecr-login.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}

          docker build -f DockerFile -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

#################################################
# JOB 5 — Deploy to ECS
#################################################
  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::227224898353:role/dev-ecs_fargate
          aws-region: ${{ env.AWS_REGION }}

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --force-new-deployment
